// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4HjOzK0igXKKcvnmmILEivmrDJ-aIK7k',
    appId: '1:241990675556:web:b3a97139addf9bdf46c371',
    messagingSenderId: '241990675556',
    projectId: 'fir-5699e',
    authDomain: 'fir-5699e.firebaseapp.com',
    storageBucket: 'fir-5699e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAki4kqqYAg61o5l7_IokTZENjwV2Fjptg',
    appId: '1:241990675556:android:c9d255e5767ea6e646c371',
    messagingSenderId: '241990675556',
    projectId: 'fir-5699e',
    storageBucket: 'fir-5699e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYceXSTOfFhkIzsbxj7Z9v_W80z0ZRPeE',
    appId: '1:241990675556:ios:d25d1d8ffa67e18346c371',
    messagingSenderId: '241990675556',
    projectId: 'fir-5699e',
    storageBucket: 'fir-5699e.appspot.com',
    iosBundleId: 'com.example.assetGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYceXSTOfFhkIzsbxj7Z9v_W80z0ZRPeE',
    appId: '1:241990675556:ios:d25d1d8ffa67e18346c371',
    messagingSenderId: '241990675556',
    projectId: 'fir-5699e',
    storageBucket: 'fir-5699e.appspot.com',
    iosBundleId: 'com.example.assetGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4HjOzK0igXKKcvnmmILEivmrDJ-aIK7k',
    appId: '1:241990675556:web:fb4e0abed493536f46c371',
    messagingSenderId: '241990675556',
    projectId: 'fir-5699e',
    authDomain: 'fir-5699e.firebaseapp.com',
    storageBucket: 'fir-5699e.appspot.com',
  );

}